= Linux Bash 编程实践
D瓜哥 <http://www.diguage.com/>
v0.0.1, 2017-2-20
:doctype: book
:icons: font
:source-highlighter: rouge
:rouge-style: monokai
:rouge-linenums-mode: table
:docinfo:
:toc: left
:toc-title: 目录
:toclevels: 4
:sectnumlevels: 4
:preface-title: 前言
:chapter-label: 章
:appendix-caption: 附录
:listing-caption: 代码
:figure-caption: 图
:version-label: V
:pdf-page-size: A4
:keywords: Linux,Bash,编程
:description: MySQL 学习笔记。从数据库表结构设计，深入到索引的数据结构，最后以前面的知识做铺垫，讲解如何使用 explain 做 SQL 的查询优化。
:last-update-label: 最后更新时间
:homepage: http://www.diguage.com/
:sourcedir: ./src/

== 

// https://stackoverflow.com/a/1583282/951836
find /home/www -type f -print0 | xargs -0 sed -i 's/subdomainA\.example\.com/subdomainB.example.com/g'

// https://stackoverflow.com/a/22385837/951836
grep -rl oldtext . | xargs sed -i 's/oldtext/newtext/g'


== 问题

. 为什么双引号可以多层嵌套？
. 为什么函数的 `exit` 没有正确退出整个脚本？

== 非贪婪匹配

https://code.i-harness.com/zh-CN/q/10d52d[regex - 非贪婪（不情愿）正则表达式在sed中匹配？ - CODE Q&A Solved]



== Get Http Status Code and body

https://superuser.com/questions/1320674/get-response-body-and-show-http-code-by-curl/1321274#1321274[bash - Get response body and show HTTP code by curl - Super User]

curl -s -w "\n%{http_code}" 'https://swapi.co/api/people/1/?format=json' | {
    read body
    read code
    echo $code
    jq .name <<< "$body"
}


== Heredoc and Variable

https://stackoverflow.com/questions/23929235/multi-line-string-with-extra-space-preserved-indentation/23930212#23930212[bash - Multi-line string with extra space (preserved indentation) - Stack Overflow]

read -r -d '' VAR << EOM
This is line 1.
This is line 2.
Line 3.
EOM



== Import Bash Script

https://stackoverflow.com/questions/10823635/how-to-include-file-in-a-bash-shell-script/10823650#10823650[linux - How to include file in a bash shell script - Stack Overflow]

source FILE

  可以定义一个 `import` 函数，来加载类库。

== Print All Arauments

https://linuxconfig.org/how-do-i-print-all-arguments-submitted-on-a-command-line-from-a-bash-script[How do I print all arguments submitted on a command line from a bash script? - LinuxConfig.org]

[source,bash]
----
#!/bin/bash 

echo $@
----

== 参数处理

=== 手动处理

[source,bash]
----
include::{sourcedir}param-manual.sh[]
----

=== 使用 `getopts` 处理

[source,bash]
----
include::{sourcedir}param-getopts.sh[]
----

=== 使用 `getopt` 处理

[source,bash]
----
include::{sourcedir}param-getopt.sh[]
----

== 使用 `sed` 跨行替换

[source,bash]
----
sed -i -f source.sed xxx.adoc
----

.`source.sed`
[source,bash]
----
include::{sourcedir}source.sed[]
----

https://github.com/spring-projects/spring-framework/pull/25545[Merge source and substitution configuration in reference docs by diguage · Pull Request #25545 · spring-projects/spring-framework^]

== 参考资料

* http://c.biancheng.net/cpp/view/2739.html[Shell特殊变量：Shell $0, $#, $*, $@, $?, $$和命令行参数_Shell中文网]
* https://my.oschina.net/leejun2005/blog/202376[bash/shell 解析命令行参数工具：getopts/getopt - leejun2005的个人页面]
* http://www.cnblogs.com/FrankTan/archive/2010/03/01/1634516.html[Bash Shell中命令行选项/参数处理 - Frank Tan - 博客园]
* https://www.cyberciti.biz/faq/bash-loop-over-file/[Bash Shell Loop Over Set of Files]
* http://www.cnblogs.com/kaituorensheng/archive/2012/12/19/2825376.html[shell编程--遍历目录下的文件 - jihite - 博客园]
